baseurl: https://iigb-bioinfocore.github.io/
title: IIGB Bioinformatics Core @ UCR
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
disqusShortname: ''
googleAnalytics: ''
summaryLength: 70
paginate: 10
pluralizelisttitles: no
publishDir: docs/
menu:
  main:
    - identifier: menu.about
      name: About
      url: /about/
      weight: 1
    - name: 'Mission'
      parent: menu.about
      url: /about/mission/
      weight: 1
    - name: 'Rates & Services'
      parent: menu.about
      url: /about/services/
      weight: 2
    - name: 'People'
      parent: menu.about
      url: /about/people/
      weight: 3
    - identifier: menu.blog
      name: News
      url: /blog/
      weight: 2
    - identifier: menu.workshops
      name: Workshops
      url: /categories/workshops/
      weight: 3
    # - identifier: menu.manuals
    #   name: Manuals
    #   url: /categories/manuals/
    #   weight: 4
    - identifier: menu.contact
      name: Contact
      url: /contact/
      weight: 8
    - identifier: menu.links
      name: Links
      url: /img/iigb-core-name.png
      weight: 8
    - identifier: section.iigb-collab
      name: IIGB Collaboration Partners
      url:
      weight: 1
      parent: menu.links
      post: 1
    - identifier: section.iigb
      name: IIGB
      url: https://iigb.ucr.edu
      weight: 1
      parent: section.iigb-collab
    - identifier: section.cepceb
      name: CEPCEB
      url: https://cepceb.ucr.edu
      weight: 2
      parent: section.iigb-collab
    - identifier: section.hpcc
      name: HPCC
      url: https://hpcc.ucr.edu
      weight: 3
      parent: section.iigb-collab
    - identifier: section.iigb-core
      name: IIGB Core Facilities
      url: 
      weight: 1
      parent: menu.links
      post: 2
    - identifier: section.genomics
      name: Genomics Core
      url: https://genomics.iigb.ucr.edu
      weight: 1
      parent: section.iigb-core
    - identifier: section.metabolomics
      name: Metabolomics Core
      url: https://metabolomics.iigb.ucr.edu
      weight: 2
      parent: section.iigb-core      
    - identifier: section.proteomics
      name: Proteomics Core
      url: https://proteomics.iigb.ucr.edu
      weight: 3
      parent: section.iigb-core      
  topbar:
    - name: Phone
      pre: <i class='fas fa-2x fa-phone'></i>
      url: tel:951-827-7990
      weight: 1
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/IIGB-BioinfoCore/
      weight: 2
    # - name: Facebook
    #   pre: <i class='fab fa-2x fa-facebook'></i>
    #   url: http://facebook.com
    #   weight: 3
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: http://twitter.com/bioinformatics
      weight: 4
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:bioinformatics@ucr.edu
      weight: 5
params:
  about_us: "<p>We are the IIGB Bioinformatics Core at UCR. We provide bioinformatics and data analysis services to UCR and the scientific community. We also provide bioinformatics training and workshops.</p>"
  address: "<p class=\"text-uppercase\"><strong>IIGB Bioinformatics Core Facility</strong>\n        
  <br>1207G Genomics building\n        
  <br>University of California, Riverside\n        
  <br>Riverside, CA 92521\n
  <br>\n     </p>" 
  author: DevCows
  carouselCustomers:
    auto_play: no
    items: 6
    pagination_speed: 1000
    slide_speed: 2000
  carouselHomepage:
    auto_play: yes
    enable: yes
    pagination_speed: 1000
    slide_speed: 2000
  carouselTestimonials:
    auto_play: no
    items: 4
    pagination_speed: 1000
    slide_speed: 2000
  clients:
    enable: no
    subtitle: ''
    title: Our Clients
  email: "bioinformatics@ucr.edu"
  contact_form_ajax: no
  contact_url: /contact
  copyright: Copyright (c) 2022, University of California, Riverside; all rights reserved.
  date_format: January 2, 2006
  default_sharing_image: img/IIGB-BC.png
  defaultDescription: "IIGB Bioinformatics core website at UCR"
  defaultKeywords:
    - "IIGB Bioinformatics"
    - "UCR"
    - blogdown
    - devcows
    - hugo
    - go
  disabled_logo: yes
  dropdown_mouse_over: no
  enableGoogleMaps: yes
  enableRecaptchaInContactForm: no
  facebook_site: ''
  features:
    cols: 3
    enable: yes
  footer:
    recent_posts:
      enable: yes
  formspree_action: https://formspree.io/f/mjvlqeyr
  googleMapsApiKey: AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY
  googleRecaptchaKey: site_key_for_google_recaptcha
  latitude: '33.971405'
  logo: img/logo.png
  logo_small: img/logo-small.png
  logo_text: IIGB-Bioinfo-Core
  longitude: '-117.326332'
  mainSections: blog
  recent_posts:
    enable: yes
    hide_summary: no
    subtitle: Check out recent IIGB and Bioinformatics core news.
    title: Recent News
  # see_more:
  #   enable: no
  #   icon: far fa-file-alt
  #   link_text: Check other homepages
  #   link_url: '#'
  #   subtitle: We have prepared for you more than 40 different HTML pages, including
  #     5 variations of homepage.
  #   title: Do you want to see more?
  # style: default
  testimonials:
    enable: no
    subtitle: We have worked with many clients and we always like to hear they come
      out from the cooperation happy and satisfied. Have a look what our clients said
      about us.
    title: Testimonials
  topbar:
    enable: yes
    text: "<p class=\"hidden-sm hidden-xs\">Contact us at (951) 827-7990 or bioinformatics@ucr.edu.</p>\n
      \     <p class=\"hidden-md hidden-lg\"><a href=\"tel:(951) 827-7990\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-phone\"></i></a>\n      <a href=\"mailto:bioinformatics@ucr.edu\"
      data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\n      </p>\n
      \     "
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:slug/
  manual: /manual/:year/:month/:day/:slug/
taxonomies:
  author: authors
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true

